# Generated by Django 4.2.7 on 2026-06-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_ref',
            field=models.CharField(blank=True, help_text='M-Pesa code or bank ref', max_length=100, unique=True),
        ),
    ]
