# Generated by Django 4.2.7 on 2026-09-20 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_payment_transaction_ref_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='property_item',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='lease',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='managementrequest',
            name='property',
        ),
        migrations.RemoveField(
            model_name='message',
            name='parent_message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='lease',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tenantdocument',
            name='lease',
        ),
        migrations.RemoveField(
            model_name='tenantdocument',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='tenantdocument',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='TenantService',
        ),
        migrations.RemoveField(
            model_name='property',
            name='landlord',
        ),
        migrations.DeleteModel(
            name='Landlord',
        ),
        migrations.DeleteModel(
            name='Lease',
        ),
        migrations.DeleteModel(
            name='MaintenanceRequest',
        ),
        migrations.DeleteModel(
            name='ManagementRequest',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
        migrations.DeleteModel(
            name='TenantDocument',
        ),
    ]
