# Generated by Django 5.2.6 on 2025-09-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_property_is_furnished_property_near_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
