# Generated by Django 5.2.6 on 2025-09-25 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_whatsappuser_whatsapppropertyrequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsapppropertyrequest',
            name='property',
        ),
        migrations.RemoveField(
            model_name='whatsapppropertyrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='WhatsAppConversation',
        ),
        migrations.DeleteModel(
            name='WhatsAppPropertyRequest',
        ),
        migrations.DeleteModel(
            name='WhatsAppUser',
        ),
    ]
