# Generated by Django 4.2.7 on 2026-09-21 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_managementrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementrequest',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_requests', to='listings.property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
