# Generated by Django 4.2.7 on 2026-09-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_managementrequest_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
