# Generated by Django 4.2.7 on 2026-09-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_property_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageHeroSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Homepage Hero', max_length=120)),
                ('hero_image', models.ImageField(blank=True, help_text='Upload the hero background image for the home page.', null=True, upload_to='homepage/')),
                ('hero_image_url', models.URLField(blank=True, help_text='Or set a direct image URL for the homepage hero.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Hero Settings',
                'verbose_name_plural': 'Homepage Hero Settings',
            },
        ),
    ]
