# Generated by Django 5.2.6 on 2025-10-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_remove_property_address_remove_property_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='main_towns',
            field=models.TextField(blank=True, help_text='Comma-separated list of main towns in this county'),
        ),
    ]
