# Generated by Django 4.2.7 on 2026-09-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_homepageherosettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageherosettings',
            name='hero_image_url',
            field=models.URLField(blank=True, default='/static/images/property2.jpg', help_text='Or set a direct image URL for the homepage hero.'),
        ),
    ]
