# Generated by Django 4.2.7 on 2025-10-10 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_county_main_towns'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyViewing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('viewing_date', models.DateField()),
                ('viewing_time', models.CharField(choices=[('09:00', '9:00 AM'), ('10:00', '10:00 AM'), ('11:00', '11:00 AM'), ('12:00', '12:00 PM'), ('13:00', '1:00 PM'), ('14:00', '2:00 PM'), ('15:00', '3:00 PM'), ('16:00', '4:00 PM'), ('17:00', '5:00 PM'), ('18:00', '6:00 PM')], help_text='Viewings only during daytime (9 AM - 6 PM)', max_length=5)),
                ('message', models.TextField(blank=True, help_text='Any special requests or questions')),
                ('number_of_people', models.PositiveIntegerField(default=1, help_text='How many people will attend the viewing')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('is_notified', models.BooleanField(default=False, help_text='Has admin been notified?')),
                ('confirmation_sent', models.BooleanField(default=False, help_text='Has confirmation been sent to customer?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewings', to='listings.property')),
            ],
            options={
                'verbose_name': 'Property Viewing',
                'verbose_name_plural': 'Property Viewings',
                'ordering': ['viewing_date', 'viewing_time'],
                'unique_together': {('property_item', 'viewing_date', 'viewing_time')},
            },
        ),
    ]
