# Generated by Django 4.2.7 on 2025-10-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_propertyviewing'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_furnished',
            field=models.BooleanField(default=False, help_text='Is the property furnished?'),
        ),
        migrations.AddField(
            model_name='property',
            name='near_school',
            field=models.BooleanField(default=False, help_text='Is property near a school?'),
        ),
        migrations.AddField(
            model_name='property',
            name='pet_friendly',
            field=models.BooleanField(default=False, help_text='Are pets allowed?'),
        ),
    ]
