# Generated by Django 4.2.7 on 2025-10-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_lease_tenant_tenantdocument_payment_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('maintenance', 'Maintenance & Repairs'), ('cleaning', 'Cleaning Services'), ('utilities', 'Utility Management'), ('security', 'Security Services'), ('lifestyle', 'Lifestyle Services'), ('support', 'Support Services')], max_length=20)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class', max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price in KSh (leave blank if free)', max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured services appear first')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant Service',
                'verbose_name_plural': 'Tenant Services',
                'ordering': ['-is_featured', 'category', 'name'],
            },
        ),
    ]
