# Generated by Django 4.2.7 on 2025-10-25 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_property_amenities'),
    ]

    operations = [
    ]
