# Generated by Django 4.2.7 on 2025-10-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_add_town_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='town',
            field=models.CharField(blank=True, help_text='Specific town or area within the county', max_length=100),
        ),
    ]
