# Generated by Django 4.2.7 on 2025-10-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_add_town_field_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(help_text='Upload team member photo (120x120px recommended)', upload_to='team/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0 = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='property',
            name='town',
        ),
    ]
