# Generated by Django 4.2.7 on 2025-10-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_add_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='town',
            field=models.CharField(blank=True, help_text='Specific town or area within the county', max_length=100),
        ),
    ]
