# Generated by Django 5.2.6 on 2025-09-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Property title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Property description')),
                ('location', models.CharField(help_text='Specific location/area', max_length=100)),
                ('county', models.CharField(help_text='County in Kenya', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Property price in KES', max_digits=12)),
                ('bedrooms', models.PositiveIntegerField(help_text='Number of bedrooms')),
                ('bathrooms', models.PositiveIntegerField(help_text='Number of bathrooms')),
                ('parking', models.PositiveIntegerField(default=0, help_text='Number of parking spaces')),
                ('area', models.DecimalField(decimal_places=2, help_text='Area in square meters', max_digits=8)),
                ('property_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('land', 'Land'), ('commercial', 'Commercial'), ('office', 'Office')], default='house', max_length=20)),
                ('main_image', models.ImageField(help_text='Main property image', upload_to='properties/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('rented', 'Rented'), ('pending', 'Pending')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
