# Generated by Django 5.2.6 on 2025-09-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('home', 'Home'), ('rental', 'Rental'), ('office', 'Office'), ('gated_community', 'Gated Community'), ('house', 'House'), ('apartment', 'Apartment'), ('land', 'Land'), ('commercial', 'Commercial')], default='home', max_length=20),
        ),
    ]
